// ═══════════════════════════════════════════════════════════════
//  DEEP SCAN CHECK DATABASES — 150+ vulnerability check points
// ═══════════════════════════════════════════════════════════════

export const SECURITY_HEADERS = [
  { name: 'strict-transport-security', desc: 'Forces HTTPS connections, prevents protocol downgrade attacks' },
  { name: 'x-frame-options', desc: 'Prevents clickjacking by controlling iframe embedding' },
  { name: 'x-content-type-options', desc: 'Prevents MIME-type sniffing attacks' },
  { name: 'content-security-policy', desc: 'Controls which resources the browser can load' },
  { name: 'referrer-policy', desc: 'Controls how much referrer info is sent with requests' },
  { name: 'permissions-policy', desc: 'Controls which browser features/APIs can be used' },
  { name: 'x-xss-protection', desc: 'Legacy XSS filter (still checked by scanners)' },
  { name: 'cross-origin-opener-policy', desc: 'Isolates browsing context from cross-origin documents' },
  { name: 'cross-origin-resource-policy', desc: 'Controls cross-origin resource loading' },
  { name: 'cross-origin-embedder-policy', desc: 'Requires CORS/CORP for cross-origin resources' },
  { name: 'cache-control', desc: 'Controls caching behavior, prevents sensitive data caching' },
  { name: 'pragma', desc: 'Legacy HTTP/1.0 cache control directive' },
  { name: 'x-permitted-cross-domain-policies', desc: 'Controls Flash/Acrobat cross-domain access' },
  { name: 'x-dns-prefetch-control', desc: 'Controls DNS prefetching behavior' },
  { name: 'expect-ct', desc: 'Certificate Transparency enforcement' },
];

export const SENSITIVE_PATHS = [
  { path: '/.env', risk: 'Critical', desc: 'Environment variables — database passwords, API keys, secrets' },
  { path: '/.env.backup', risk: 'Critical', desc: 'Backup of environment file with credentials' },
  { path: '/.env.local', risk: 'Critical', desc: 'Local environment overrides with secrets' },
  { path: '/.env.production', risk: 'Critical', desc: 'Production environment variables exposed' },
  { path: '/.git/config', risk: 'Critical', desc: 'Git config — exposes repo structure, credentials' },
  { path: '/.git/HEAD', risk: 'Critical', desc: 'Git HEAD — confirms .git directory exposure' },
  { path: '/.gitignore', risk: 'Medium', desc: 'Gitignore — reveals project structure and sensitive paths' },
  { path: '/.svn/entries', risk: 'Critical', desc: 'SVN metadata — source code exposure' },
  { path: '/.hg/store', risk: 'Critical', desc: 'Mercurial repo — source code exposure' },
  { path: '/wp-config.php', risk: 'Critical', desc: 'WordPress config — database credentials, auth keys' },
  { path: '/wp-config.php.bak', risk: 'Critical', desc: 'WordPress config backup — credentials in plaintext' },
  { path: '/wp-config.php~', risk: 'Critical', desc: 'WordPress config editor backup' },
  { path: '/configuration.php', risk: 'Critical', desc: 'Joomla config — database credentials' },
  { path: '/config.php', risk: 'Critical', desc: 'PHP config — may contain database credentials' },
  { path: '/config.yml', risk: 'High', desc: 'YAML config — may contain API keys and secrets' },
  { path: '/config.json', risk: 'High', desc: 'JSON config — may contain credentials' },
  { path: '/.htpasswd', risk: 'Critical', desc: 'Apache password file — hashed credentials' },
  { path: '/.htaccess', risk: 'High', desc: 'Apache config — reveals URL rules and restrictions' },
  { path: '/web.config', risk: 'High', desc: 'IIS config — reveals server configuration' },
  { path: '/phpinfo.php', risk: 'High', desc: 'PHP info — reveals full server configuration' },
  { path: '/info.php', risk: 'High', desc: 'PHP info variant — server configuration exposure' },
  { path: '/server-status', risk: 'High', desc: 'Apache status — active connections, internal URLs' },
  { path: '/server-info', risk: 'High', desc: 'Apache info — full server configuration' },
  { path: '/robots.txt', risk: 'Info', desc: 'Robots file — may reveal hidden directories' },
  { path: '/sitemap.xml', risk: 'Info', desc: 'Sitemap — reveals full site structure' },
  { path: '/crossdomain.xml', risk: 'Medium', desc: 'Flash cross-domain policy — unauthorized access' },
  { path: '/clientaccesspolicy.xml', risk: 'Medium', desc: 'Silverlight cross-domain policy' },
  { path: '/.well-known/security.txt', risk: 'Info', desc: 'Security contact info' },
  { path: '/backup.sql', risk: 'Critical', desc: 'Database dump — full database with all data' },
  { path: '/database.sql', risk: 'Critical', desc: 'Database dump — credentials and user data' },
  { path: '/dump.sql', risk: 'Critical', desc: 'SQL dump — complete database export' },
  { path: '/db.sql', risk: 'Critical', desc: 'Database file — full data exposure' },
  { path: '/backup.zip', risk: 'Critical', desc: 'Compressed backup — may contain entire site' },
  { path: '/backup.tar.gz', risk: 'Critical', desc: 'Compressed backup archive' },
  { path: '/site.tar.gz', risk: 'Critical', desc: 'Full site backup archive' },
  { path: '/debug.log', risk: 'High', desc: 'Debug log — stack traces, credentials, paths' },
  { path: '/error.log', risk: 'High', desc: 'Error log — internal server errors and paths' },
  { path: '/access.log', risk: 'High', desc: 'Access log — reveals user activity and IPs' },
  { path: '/wp-debug.log', risk: 'High', desc: 'WordPress debug log — PHP errors and paths' },
  { path: '/error_log', risk: 'High', desc: 'Server error log — internal paths and errors' },
  { path: '/composer.json', risk: 'Medium', desc: 'PHP dependencies — reveals packages and versions' },
  { path: '/composer.lock', risk: 'Medium', desc: 'PHP locked dependencies with exact versions' },
  { path: '/package.json', risk: 'Medium', desc: 'Node.js dependencies — reveals tech stack' },
  { path: '/package-lock.json', risk: 'Medium', desc: 'Node.js locked deps with exact versions' },
  { path: '/yarn.lock', risk: 'Medium', desc: 'Yarn locked dependencies' },
  { path: '/Gemfile', risk: 'Medium', desc: 'Ruby dependencies — reveals framework version' },
  { path: '/requirements.txt', risk: 'Medium', desc: 'Python dependencies — reveals packages' },
  { path: '/Dockerfile', risk: 'Medium', desc: 'Docker config — reveals infrastructure setup' },
  { path: '/docker-compose.yml', risk: 'High', desc: 'Docker compose — may contain credentials' },
  { path: '/.dockerignore', risk: 'Low', desc: 'Docker ignore — reveals project structure' },
  { path: '/Makefile', risk: 'Low', desc: 'Build file — reveals build process' },
  { path: '/README.md', risk: 'Low', desc: 'Readme — may reveal internal documentation' },
  { path: '/CHANGELOG.md', risk: 'Low', desc: 'Changelog — reveals version history' },
  { path: '/LICENSE', risk: 'Info', desc: 'License file' },
  { path: '/xmlrpc.php', risk: 'High', desc: 'WordPress XML-RPC — brute force and DDoS vector' },
  { path: '/wp-cron.php', risk: 'Medium', desc: 'WordPress cron — can be abused for DDoS' },
  { path: '/install.php', risk: 'Critical', desc: 'Installation script — may allow re-installation' },
  { path: '/setup.php', risk: 'Critical', desc: 'Setup script — may allow reconfiguration' },
  { path: '/test.php', risk: 'High', desc: 'Test script — may expose debug information' },
  { path: '/phpunit.xml', risk: 'Medium', desc: 'PHPUnit config — reveals test configuration' },
  { path: '/.DS_Store', risk: 'Medium', desc: 'macOS directory file — reveals file structure' },
  { path: '/Thumbs.db', risk: 'Low', desc: 'Windows thumbnail cache — information leak' },
  { path: '/.vscode/settings.json', risk: 'Medium', desc: 'VS Code settings — reveals dev configuration' },
  { path: '/.idea/workspace.xml', risk: 'Medium', desc: 'JetBrains IDE config — dev environment' },
  { path: '/sftp-config.json', risk: 'Critical', desc: 'SFTP credentials in plaintext' },
  { path: '/id_rsa', risk: 'Critical', desc: 'SSH private key — full server access' },
  { path: '/.ssh/authorized_keys', risk: 'Critical', desc: 'SSH authorized keys file' },
  { path: '/wp-content/debug.log', risk: 'High', desc: 'WordPress debug log in content dir' },
];

export const ADMIN_PANELS = [
  { path: '/wp-admin', name: 'WordPress Admin' },
  { path: '/wp-login.php', name: 'WordPress Login' },
  { path: '/admin', name: 'Admin Panel' },
  { path: '/admin/', name: 'Admin Directory' },
  { path: '/administrator', name: 'Joomla Admin' },
  { path: '/admin/login', name: 'Admin Login' },
  { path: '/user/login', name: 'User Login' },
  { path: '/phpmyadmin', name: 'phpMyAdmin' },
  { path: '/pma', name: 'phpMyAdmin (alias)' },
  { path: '/cpanel', name: 'cPanel' },
  { path: '/webmail', name: 'Webmail' },
  { path: '/login', name: 'Login Page' },
  { path: '/signin', name: 'Sign-In Page' },
  { path: '/dashboard', name: 'Dashboard' },
  { path: '/panel', name: 'Control Panel' },
  { path: '/manage', name: 'Management Panel' },
  { path: '/manager', name: 'Manager Panel' },
  { path: '/adminer.php', name: 'Adminer DB Tool' },
  { path: '/_admin', name: 'Hidden Admin' },
  { path: '/controlpanel', name: 'Control Panel' },
];

export const KNOWN_TRACKERS = [
  { name: 'Google Analytics', patterns: ['google-analytics.com', 'www.google-analytics.com/analytics.js', 'www.googletagmanager.com/gtag'], type: 'Analytics' },
  { name: 'Google Tag Manager', patterns: ['googletagmanager.com/gtm'], type: 'Tag Manager' },
  { name: 'Meta / Facebook Pixel', patterns: ['connect.facebook.net', 'facebook.com/tr'], type: 'Marketing' },
  { name: 'TikTok Pixel', patterns: ['analytics.tiktok.com'], type: 'Marketing' },
  { name: 'LinkedIn Insight Tag', patterns: ['snap.licdn.com', 'linkedin.com/px'], type: 'Marketing' },
  { name: 'Microsoft Clarity', patterns: ['clarity.ms'], type: 'Analytics' },
  { name: 'Hotjar', patterns: ['hotjar.com', 'static.hotjar.com'], type: 'Analytics' },
  { name: 'Bing UET', patterns: ['bat.bing.com'], type: 'Marketing' },
  { name: 'Google Ads / DoubleClick', patterns: ['doubleclick.net', 'googlesyndication.com', 'googleadservices.com'], type: 'Advertising' },
  { name: 'Pinterest Tag', patterns: ['pinimg.com/ct', 'ct.pinterest.com'], type: 'Marketing' },
  { name: 'Twitter / X Pixel', patterns: ['ads-twitter.com', 'analytics.twitter.com'], type: 'Marketing' },
  { name: 'Snapchat Pixel', patterns: ['sc-static.net'], type: 'Marketing' },
  { name: 'Hubspot Tracking', patterns: ['js.hs-scripts.com', 'js.hs-analytics.net'], type: 'Marketing' },
  { name: 'Intercom', patterns: ['widget.intercom.io', 'intercom.io'], type: 'Analytics' },
  { name: 'Drift', patterns: ['js.driftt.com'], type: 'Marketing' },
  { name: 'Segment', patterns: ['cdn.segment.com', 'api.segment.io'], type: 'Analytics' },
  { name: 'Mixpanel', patterns: ['cdn.mxpnl.com', 'mixpanel.com'], type: 'Analytics' },
  { name: 'Heap Analytics', patterns: ['heap.io', 'cdn.heapanalytics.com'], type: 'Analytics' },
  { name: 'Amplitude', patterns: ['cdn.amplitude.com', 'amplitude.com'], type: 'Analytics' },
  { name: 'Crazy Egg', patterns: ['crazyegg.com', 'script.crazyegg.com'], type: 'Analytics' },
];

export const INLINE_TRACKER_SIGS = [
  { name: 'Meta / Facebook Pixel', pattern: 'fbq(', type: 'Marketing' },
  { name: 'Google Analytics (gtag)', pattern: 'gtag(', type: 'Analytics' },
  { name: 'Google Analytics (ga())', pattern: "ga('send", type: 'Analytics' },
  { name: 'TikTok Pixel', pattern: 'ttq.load', type: 'Marketing' },
  { name: 'Hotjar', pattern: 'hj(', type: 'Analytics' },
  { name: 'LinkedIn Insight', pattern: '_linkedin_partner_id', type: 'Marketing' },
  { name: 'Microsoft Clarity', pattern: 'clarity(', type: 'Analytics' },
  { name: 'Pinterest Tag', pattern: 'pintrk(', type: 'Marketing' },
  { name: 'Hubspot', pattern: '_hsq.push', type: 'Marketing' },
];

export const TECH_SIGNATURES = [
  { name: 'WordPress', patterns: ['wp-content', 'wp-includes', 'wp-json'], category: 'CMS' },
  { name: 'Joomla', patterns: ['/media/jui/', '/components/com_'], category: 'CMS' },
  { name: 'Drupal', patterns: ['Drupal.settings', '/sites/default/', '/core/misc/drupal'], category: 'CMS' },
  { name: 'Magento', patterns: ['mage/', 'Magento_', '/static/frontend/Magento'], category: 'E-Commerce' },
  { name: 'Shopify', patterns: ['cdn.shopify.com', 'shopify-section'], category: 'E-Commerce' },
  { name: 'WooCommerce', patterns: ['woocommerce', 'wc-ajax'], category: 'E-Commerce' },
  { name: 'Wix', patterns: ['static.wixstatic.com', 'wix.com'], category: 'Website Builder' },
  { name: 'Squarespace', patterns: ['squarespace.com', 'static1.squarespace.com'], category: 'Website Builder' },
  { name: 'Webflow', patterns: ['assets.website-files.com', 'webflow.com'], category: 'Website Builder' },
  { name: 'React', patterns: ['react.production.min', 'reactroot', '_reactRootContainer'], category: 'Framework' },
  { name: 'Next.js', patterns: ['__NEXT_DATA__', '_next/static'], category: 'Framework' },
  { name: 'Nuxt.js', patterns: ['__NUXT__', '_nuxt/'], category: 'Framework' },
  { name: 'Vue.js', patterns: ['vue.runtime', '__vue__', 'vue-router'], category: 'Framework' },
  { name: 'Angular', patterns: ['ng-version', 'angular.min', 'ng-app'], category: 'Framework' },
  { name: 'Svelte', patterns: ['svelte', '__svelte'], category: 'Framework' },
  { name: 'jQuery', patterns: ['jquery.min.js', 'jquery-', 'jQuery('], category: 'Library' },
  { name: 'Bootstrap', patterns: ['bootstrap.min.css', 'bootstrap.min.js'], category: 'Library' },
  { name: 'Tailwind CSS', patterns: ['tailwindcss', 'tw-'], category: 'Library' },
  { name: 'Cloudflare', patterns: ['cf-ray', 'cloudflare'], category: 'CDN/Security' },
  { name: 'AWS CloudFront', patterns: ['cloudfront.net', 'x-amz-cf'], category: 'CDN' },
  { name: 'Nginx', patterns: ['nginx'], category: 'Server' },
  { name: 'Apache', patterns: ['apache', 'mod_'], category: 'Server' },
  { name: 'PHP', patterns: ['x-powered-by: php', '.php'], category: 'Language' },
  { name: 'ASP.NET', patterns: ['x-aspnet-version', 'asp.net', '__VIEWSTATE'], category: 'Framework' },
  { name: 'Laravel', patterns: ['laravel_session', 'laravel'], category: 'Framework' },
  { name: 'Express.js', patterns: ['x-powered-by: express'], category: 'Framework' },
  { name: 'Google Fonts', patterns: ['fonts.googleapis.com', 'fonts.gstatic.com'], category: 'CDN' },
  { name: 'Font Awesome', patterns: ['fontawesome', 'font-awesome'], category: 'Library' },
  { name: 'reCAPTCHA', patterns: ['google.com/recaptcha', 'recaptcha'], category: 'Security' },
  { name: 'hCaptcha', patterns: ['hcaptcha.com'], category: 'Security' },
];

export const DANGEROUS_HTTP_METHODS = ['PUT', 'DELETE', 'TRACE', 'CONNECT', 'PATCH'];
